In [2]:
import pandas as pd
import numpy as np

In [28]:
X = np.array([[1,0,0,0],[1,0,1,0],[1,1,0,0],[1,1,1,1]])
X



array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [29]:
target = np.array([0,1,1,0])
target

array([0, 1, 1, 0])

In [30]:
weights = np.array([-0.6, 2, 1.2, -2.8])
weights

array([-0.6,  2. ,  1.2, -2.8])

In [31]:
def sigmoid_function():

    return

In [32]:
def loss_function():

    return

In [33]:
def gradient():

    return

In [ ]:
alpha = 0.1 # learning rate
iterations = 10

for i in range(iterations):
    Z = np.dot(weights, X)
    sigmoid = sigmoid_function(Z)
    loss = loss_function(sigmoid, target)
    gradient = gradient(sigmoid, X, target)

    w = w - (alpha * gradient)

    print()




[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
[-0.2 -1.6 -0.8 -2.8]
