In [131]:
import pandas as pd
import numpy as np
import math

In [132]:
X = np.array([[1,0,0,0],
              [1,0,1,0],
              [1,1,0,0],
              [1,1,1,1]])
X



array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [133]:
target = np.array([0,1,1,0])
target

array([0, 1, 1, 0])

In [134]:
weights = np.array([-0.6, 2, 1.2, -2.8])
weights

array([-0.6,  2. ,  1.2, -2.8])

In [135]:
def sigmoid_function(z):
    result = 1/ (1 + math.e**(-z))
    return result

In [136]:
def loss_function(y, t):
    result = -(t * np.log(y) + (1 - t) * np.log(1 - y))
    return result

In [137]:
def gradient(y, t, X, alpha):
    result = alpha * np.dot(X.T, (y - t)) / len(t)
    return result

In [ ]:
alpha = 0.1 # learning rate
iterations = 10
print(f'i, Weights, z-value, y-value, loss-value')

for i in range(iterations):
    Z = np.dot(X, weights)
    sigmoid = sigmoid_function(Z)
    loss = loss_function(sigmoid, target)
    gradient_value = gradient(sigmoid, target, X, alpha)
    weights -= gradient_value
    # print(gradient_value)
    print(f'{i}.\n Weights: {weights} \n Z-value:{Z},\n Y-value{sigmoid},\n Loss_value:{loss}\n')
    



## IF YOU ARE RUNNING THE CODE MAKE SURE YOU RESENT THE WEIGHTS BY RUNNING CELL 4 AGAIN.
## OTHERWISE THE W WILL KEEP GETTING UPDATED WITHOUT GOING BACK TO THE ORIGINAL FORM IF YOU WANT TO RUN AGAIN




i, Weights, z-value, y-value, loss-value
0.
 Weights: [-0.60630875  1.99369125  1.19760444 -2.81125415] 
 Z-value:[-0.6  0.6  1.4 -0.2],
 Y-value[0.35434369 0.64565631 0.80218389 0.450166  ],
 Loss_value:[0.43748795 0.43748795 0.22041741 0.59813887]

1.
 Weights: [-0.61231903  1.98759507  1.19542105 -2.82234598] 
 Z-value:[-0.60630875  0.59129569  1.38738251 -0.2262672 ],
 Y-value[0.35290168 0.64366238 0.80017405 0.44367331],
 Loss_value:[0.43525704 0.44058094 0.22292602 0.58639958]

2.
 Weights: [-0.61804304  1.98170385  1.19344109 -2.83328143] 
 Z-value:[-0.61231903  0.58310202  1.37527604 -0.2516489 ],
 Y-value[0.35153038 0.64178087 0.79823124 0.43741769],
 Loss_value:[0.43314012 0.44350836 0.22535695 0.57521783]

3.
 Weights: [-0.62349252  1.97601023  1.19165612 -2.84406619] 
 Z-value:[-0.61804304  0.57539805  1.36366081 -0.27617953],
 Y-value[0.35022666 0.64000781 0.79635403 0.43139066],
 Loss_value:[0.43113169 0.4462749  0.22771143 0.56456166]

4.
 Weights: [-0.62867881  1.970507