In [37]:
import pandas as pd
import numpy as np

In [38]:
X = np.array([[1,0,0,0],
              [1,0,1,0],
              [1,1,0,0],
              [1,1,1,1]])
X



array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [39]:
target = np.array([0,1,1,0])
target

array([0, 1, 1, 0])

In [40]:
weights = np.array([-0.6, 2, 1.2, -2.8])
weights

array([-0.6,  2. ,  1.2, -2.8])

In [41]:
def sigmoid_function(z):
    result = 1/ (1 + np.exp(-z))
    return result

In [42]:
def loss_function(y, t):
    result = -(t * np.log(y) + (1 - t) * np.log(1 - y))
    return result

In [43]:
def gradient(y, t, X, alpha):
    result = alpha * np.dot(X.T, (y - t)) / len(t)
    return result

In [44]:
alpha = 0.1 # learning rate
iterations = 10
print(f'i, z-value, y-value, loss-value')

for i in range(iterations):
    print(f'weights: {weights}')
    Z = np.dot(weights, X)
    sigmoid = sigmoid_function(Z)
    loss = loss_function(sigmoid, target)
    gradient_value = gradient(sigmoid, target, X, alpha)
    weights -= gradient_value
    # print(gradient_value)
    print(f'{i}.\n Z-value:{Z},\n Y-value{sigmoid},\n Loss_value:{loss}\n')
    






i, z-value, y-value, loss-value
weights: [-0.6  2.   1.2 -2.8]
0.
 Z-value:[-0.2 -1.6 -0.8 -2.8],
 Y-value[0.450166   0.16798161 0.31002552 0.05732418],
 Loss_value:[0.59813887 1.78390074 1.17110067 0.05903283]

weights: [-0.57463743  2.01581626  1.21936736 -2.8014331 ]
1.
 Z-value:[-0.14088692 -1.58206575 -0.78561685 -2.8014331 ],
 Y-value[0.46483641 0.17050312 0.31311059 0.05724678],
 Loss_value:[0.62518281 1.76900168 1.16119882 0.05895073]

weights: [-0.54977986  2.03155732  1.23867361 -2.80286427]
2.
 Z-value:[-0.0824132  -1.56419067 -0.77130695 -2.80286427],
 Y-value[0.47940835 0.17304614 0.31619645 0.05716959],
 Loss_value:[0.65278933 1.75419704 1.15139157 0.05886886]

weights: [-0.52542537  2.04722317  1.25791821 -2.80429351]
3.
 Z-value:[-0.0245775  -1.5463753  -0.75707034 -2.80429351],
 Y-value[0.49385594 0.1756104  0.31928266 0.0570926 ],
 Loss_value:[0.68093394 1.73948735 1.14167847 0.0587872 ]

weights: [-0.50157141  2.06281379  1.27710064 -2.80572083]
4.
 Z-value:[ 0.03262