In [22]:
import pandas as pd
import numpy as np

In [23]:
X = np.array([[1,0,0,0],[1,0,1,0],[1,1,0,0],[1,1,1,1]])
X



array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [24]:
target = np.array([0,1,1,0])
target

array([0, 1, 1, 0])

In [25]:
weights = np.array([-0.6, 2, 1.2, -2.8])
weights

array([-0.6,  2. ,  1.2, -2.8])

In [26]:
def sigmoid_function(z):
    result = 1/ (1 + np.exp(-z))
    return result

In [27]:
def loss_function(y, t):
    result = -np.mean(t*np.log(y) + (1-t)*np.log(1-y))
    return result

In [28]:
def gradient(y, t, X, alpha):
    result = alpha * np.dot(X.T, (y - t)) / len(t)
    return result

In [36]:
alpha = 0.1 # learning rate
iterations = 10

print(f'i, z-value, y-value, loss-value')

for i in range(iterations):
    Z = np.dot(weights, X)
    sigmoid = sigmoid_function(Z)
    loss = loss_function(sigmoid, target)
    gradient_value = gradient(sigmoid, target, X, alpha)
    weights -= gradient_value
    # print(gradient_value)
    print(f'{i}. {Z}, {sigmoid}, {loss}')
    






i, z-value, y-value, loss-value
0. [ 0.8807462  -1.25102206 -0.52404878 -2.82835531], [0.70697683 0.22252327 0.37190598 0.055811  ], 0.9441925819174679
1. [ 0.92776921 -1.23437569 -0.51113698 -2.82975059], [0.71662249 0.22541649 0.37492703 0.05573752], 0.9472889439374806
2. [ 0.97426272 -1.21779798 -0.49829703 -2.83114402], [0.72596833 0.2283242  0.37794096 0.05566423], 0.9504477844877695
3. [ 1.02023384 -1.2012893  -0.48552877 -2.83253563], [0.73501815 0.23124594 0.38094744 0.05559113], 0.9536643364268226
4. [ 1.0656896  -1.18485    -0.47283201 -2.83392541], [0.74377633 0.23418127 0.38394616 0.05551821], 0.9569340276224911
5. [ 1.110637   -1.16848045 -0.46020658 -2.83531336], [0.75224785 0.23712976 0.38693682 0.05544547], 0.9602524789269016
6. [ 1.15508293 -1.15218096 -0.44765227 -2.8366995 ], [0.76043811 0.24009095 0.3899191  0.05537292], 0.9636155012339616
7. [ 1.19903418 -1.13595188 -0.43516889 -2.83808382], [0.76835292 0.24306438 0.39289273 0.05530056], 0.9670190917676257
8. [ 1.2