In [2]:
import pandas as pd
import numpy as np

In [19]:
feature_df = np.array([[1,0,0,0],[1,0,1,0],[1,1,0,0],[1,1,1,1]])
feature_df



array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [20]:
target_vector = np.array([0,1,1,0])
target_vector

array([0, 1, 1, 0])

In [21]:
weights = np.array([-0.6, 2, 1.2, -2.8])
weights

array([-0.6,  2. ,  1.2, -2.8])

In [ ]:
def z_function():

    return

In [24]:
def sigmoid_function():

    return

In [26]:
def loss_function():

    return

In [27]:
def gradient():

    return

In [ ]:
alpha = 0.1 # learning rate
iterations = 10

