In [1]:
import pandas as pd
import numpy as np

In [2]:
X = np.array([[1,0,0,0],[1,0,1,0],[1,1,0,0],[1,1,1,1]])
X



array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [3]:
target = np.array([0,1,1,0])
target

array([0, 1, 1, 0])

In [4]:
weights = np.array([-0.6, 2, 1.2, -2.8])
weights

array([-0.6,  2. ,  1.2, -2.8])

In [5]:
def sigmoid_function(z):
    result = 1/ (1 + np.exp(-z))
    return result

In [6]:
def loss_function(y, t):
    result = -np.mean(t*np.log(y) + (1-t)*np.log(1-y))
    return result

In [7]:
def gradient(y, t, X, alpha):
    result = alpha * np.dot(X.T, (y - t)) / len(t)
    return result

In [8]:
alpha = 0.1 # learning rate
iterations = 10

for i in range(iterations):
    Z = np.dot(weights, X)
    sigmoid = sigmoid_function(Z)
    loss = loss_function(sigmoid, target)
    gradient_value = gradient(sigmoid, target, X, alpha)

    weights = weights - gradient_value

    print()


